apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  postgresql.server.name: ${POSTGRESQL_SERVER_NAME}
  postgresql.user: ${POSTGRESQL_USER}
  postgresql.password: ${POSTGRESQL_PASSWORD}
